### ISSUE TITLE
Add OSX builds

### ISSUE THREAD

**Issue by jetuk** [pywr/pywr-deploy#4]
The following PR will enable OSX builds and testing for pywr. We should then be able to add OSX for deployment in future.

https://github.com/pywr/pywr/pull/589

**Comment by snorfalorpagus** [comment]
Failing on OS X:

```
[ERROR] file /Users/travis/miniconda3/conda-bld/linux-64/*.tar.bz2 does not exist
```

**Comment by jetuk** [comment]
What should this be?

**Comment by jetuk** [comment]
This is complete.
